//! Linter/compiler/tooling control comments, ported from
//! src/unwaffle/directives.py. Functional, not prose: never judged, never
//! suggested for removal, outside gate statistics.

use std::collections::HashMap;
use std::sync::OnceLock;

use regex::Regex;

use crate::model::Kind;

const COMMON: &[&str] = &[
    r"^#\s*(region|endregion)\b",
    r"^(LCOV|GCOV|GCOVR)_EXCL_\w+",
    r"^coverage:(ignore|off|on)(-line|-start|-end|-file)?\b",
    r"^NOSONAR\b",
    r"(?i)^falls?[ -]?thr(ough|u)\.?$",
];

// NOLINT is handled in code: its python pattern needs a negative lookahead
// ("NOLINT: <prose>" stays judged) and this regex engine has none
const C_FAMILY: &[&str] = &[
    r"^clang-format\s+(on|off)\b",
    r"^cppcheck-suppress\b",
    r"^IWYU pragma:",
    r"^coverity\[",
    r"^PRQA\b",
];

const JS_FAMILY: &[&str] = &[
    r"^@ts-(ignore|expect-error|nocheck|check)\b",
    r"^eslint\b",
    r"^eslint-",
    r"^prettier-ignore\b",
    r"^(biome|rome)-ignore\b",
    r"^deno-lint-ignore\b",
    r"^@?vite-ignore\b",
    r"^webpack[A-Z]\w*:",
    r"^[@#]__PURE__$",
    r"^#\s*source(MappingURL|URL)=",
    r"^(istanbul|c8|v8)\s+ignore\b",
    r"^@(jest|vitest)-environment\b",
    r"^@jsx\b",
    r"^@flow\b",
    r"^\$Flow\w*",
    r"^@(license|preserve)\b",
    r"^@type\s",
    r"^@satisfies\s",
];

// only meaningful as block comments; guarded separately so prose line
// comments starting with "global ..." are not exempted
const JS_BLOCK_ONLY: &[&str] = &[
    r"^globals?\s+[A-Za-z_$][\w$.]*([\s,:].*)?$",
    r"^exported\s+[A-Za-z_$][\w$]*\s*$",
];

const GO: &[&str] = &[
    r"^go:[a-z]",
    r"^\+build\b",
    r"^nolint\b",
    r"^lint:(ignore|file-ignore)\b",
    r"^#cgo\b",
    r"^export\s+\w+$",
];

const RUST_LANG: &[&str] = &[r"^rustfmt::skip\b", r"^@\s"];

// patterns see content AFTER the single leading '#' is stripped, so a
// shebang arrives as "!/usr/bin/env python" and "# noqa" as "noqa"
const PYTHON: &[&str] = &[
    r"^!\s*/",
    r"^-\*-.*-\*-\s*$",
    r"^(en)?coding[:=]\s*[-\w.]+\s*$",
    r"^vim?:\s?",
    r"^noqa\b",
    r"^type:\s",
    r"^mypy:\s",
    r"^pylint:\s*(disable|enable|skip-file)",
    r"^ruff:\s*(noqa|isort)",
    r"^flake8:\s*noqa",
    r"^fmt:\s*(off|on|skip)\b",
    r"^isort:\s*(skip|skip_file|off|on|split|dont[- ]add[- ]imports)",
    r"^yapf:\s*(disable|enable)",
    r"^pragma:\s*\S",
    r"^nosec\b",
    r"^noinspection\s",
    r"^cython:\s",
    r"^(end)?region\b(\s+[\w-]+)?$",
];

const JVM: &[&str] = &[
    r"(?i)^checkstyle[:.]\s*(off|on)\b",
    r"^@formatter:(off|on)\b",
    r"^spotless:(off|on)\b",
    r"^noinspection\s",
    r"^\$NON-NLS-\d+\$",
];

const KOTLIN_EXTRA: &[&str] = &[r"^ktlint-disable\b", r"^ktlint-enable\b"];

const CSHARP: &[&str] = &[r"^ReSharper (disable|restore)\b", r"^<auto-generated"];

const SWIFT: &[&str] = &[
    r"^swiftlint:(disable|enable)\b",
    r"^swiftformat:(disable|enable|options)\b",
    r"^sourcery:",
    r"^periphery:ignore\b",
    r"^MARK:",
];

fn compiled() -> &'static HashMap<&'static str, Vec<Regex>> {
    static MAP: OnceLock<HashMap<&'static str, Vec<Regex>>> = OnceLock::new();
    MAP.get_or_init(|| {
        let build = |extra: &[&[&str]]| -> Vec<Regex> {
            COMMON
                .iter()
                .chain(extra.iter().flat_map(|e| e.iter()))
                .map(|p| Regex::new(p).unwrap())
                .collect()
        };
        HashMap::from([
            ("c", build(&[C_FAMILY])),
            ("cpp", build(&[C_FAMILY])),
            ("javascript", build(&[JS_FAMILY])),
            ("typescript", build(&[JS_FAMILY])),
            ("tsx", build(&[JS_FAMILY])),
            ("go", build(&[GO])),
            ("rust", build(&[RUST_LANG])),
            ("python", build(&[PYTHON])),
            ("java", build(&[JVM])),
            ("kotlin", build(&[JVM, KOTLIN_EXTRA])),
            ("csharp", build(&[CSHARP])),
            ("swift", build(&[SWIFT])),
        ])
    })
}

fn block_patterns() -> &'static Vec<Regex> {
    static V: OnceLock<Vec<Regex>> = OnceLock::new();
    V.get_or_init(|| JS_BLOCK_ONLY.iter().map(|p| Regex::new(p).unwrap()).collect())
}

/// "NOLINT", "NOLINTNEXTLINE(category)" etc., but not "NOLINT: <prose>".
fn is_nolint(line: &str, lang: &str) -> bool {
    if !matches!(lang, "c" | "cpp") {
        return false;
    }
    let rest = ["NOLINTNEXTLINE", "NOLINTBEGIN", "NOLINTEND", "NOLINT"]
        .iter()
        .find_map(|p| line.strip_prefix(p));
    match rest {
        Some(rest) => {
            !rest.chars().next().is_some_and(|c| c.is_alphanumeric() || c == '_')
                && !rest.trim_start().starts_with(':')
        }
        None => false,
    }
}

/// True if a comment's first content line is a tooling directive.
pub fn is_directive_text(first_line: &str, lang: &str, kind: Option<Kind>) -> bool {
    let line = first_line.trim();
    if line.is_empty() {
        return false;
    }
    if is_nolint(line, lang) {
        return true;
    }
    if compiled().get(lang).is_some_and(|v| v.iter().any(|rx| rx.is_match(line))) {
        return true;
    }
    if kind != Some(Kind::Line)
        && matches!(lang, "javascript" | "typescript" | "tsx")
        && block_patterns().iter().any(|rx| rx.is_match(line))
    {
        return true;
    }
    false
}

/// A Go comment directly above `import "C"` is the cgo preamble: it is C
/// code by design and must never be treated as commented-out code.
pub fn is_cgo_preamble(lang: &str, attached_code: &str) -> bool {
    lang == "go"
        && attached_code
            .trim()
            .strip_prefix("import")
            .is_some_and(|r| r.starts_with(char::is_whitespace) && r.trim_start().starts_with("\"C\""))
}
