//! Input filtering, ported from src/unwaffle/filtering.py: include/exclude
//! globs and the generated-file heuristic. Gitignore batching and cachedir
//! tags follow with the CLI slice.

use std::io::Read;
use std::path::Path;

use crate::config::Config;

/// fnmatch-style match of one path component (no '/' inside).
fn component_match(part: &str, pat: &str) -> bool {
    fn inner(p: &[char], t: &[char]) -> bool {
        match (p.first(), t.first()) {
            (None, None) => true,
            (Some('*'), _) => inner(&p[1..], t) || (!t.is_empty() && inner(p, &t[1..])),
            (Some('?'), Some(_)) => inner(&p[1..], &t[1..]),
            (Some(a), Some(b)) => a == b && inner(&p[1..], &t[1..]),
            _ => false,
        }
    }
    let p: Vec<char> = pat.chars().collect();
    let t: Vec<char> = part.chars().collect();
    inner(&p, &t)
}

/// Whole-path glob where '**' crosses directory boundaries and '*' does not.
fn path_match(segments: &[&str], pats: &[&str]) -> bool {
    match pats.first() {
        None => segments.is_empty(),
        Some(&"**") => {
            (0..=segments.len()).any(|skip| path_match(&segments[skip..], &pats[1..]))
        }
        Some(pat) => {
            !segments.is_empty()
                && component_match(segments[0], pat)
                && path_match(&segments[1..], &pats[1..])
        }
    }
}

/// Gitignore-flavored matching: a pattern without '/' matches any single
/// path component; one with '/' matches the whole path relative to the
/// scan root.
pub fn matches_any(rel_posix: &str, patterns: &[String]) -> bool {
    let parts: Vec<&str> = rel_posix.split('/').filter(|s| !s.is_empty()).collect();
    for pattern in patterns {
        let pat = pattern.trim_matches('/');
        if !pat.contains('/') {
            if parts.iter().any(|part| component_match(part, pat)) {
                return true;
            }
        } else {
            let pats: Vec<&str> = pat.split('/').collect();
            if path_match(&parts, &pats) {
                return true;
            }
        }
    }
    false
}

/// True when include (if any) matches and no exclude matches.
pub fn selected(rel_posix: &str, cfg: &Config) -> bool {
    if !cfg.include.is_empty() && !matches_any(rel_posix, &cfg.include) {
        return false;
    }
    !matches_any(rel_posix, &cfg.exclude)
}

// strong generated-code signals only: the classic marker stays
// case-sensitive so a stray human "do not edit this list" cannot silently
// skip a whole file
const GENERATED_UPPER: &str = "DO NOT EDIT";
const GENERATED_ANY_CASE: &[&str] =
    &["@generated", "automatically generated", "auto-generated file", "<auto-generated"];

/// Generated-file heuristic: a marker within the first 2KB.
pub fn is_generated(path: &Path) -> bool {
    let Ok(mut fh) = std::fs::File::open(path) else { return false };
    let mut buf = [0u8; 2048];
    let n = fh.read(&mut buf).unwrap_or(0);
    let head = String::from_utf8_lossy(&buf[..n]);
    if head.contains(GENERATED_UPPER) {
        return true;
    }
    let lower = head.to_lowercase();
    GENERATED_ANY_CASE.iter().any(|m| lower.contains(m))
}
