"""Input filtering: include/exclude globs, gitignore, generated files."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from uncomment.cli import discover_files, main
from uncomment.config import Config, load_config
from uncomment.filtering import is_generated, matches_any, selected
from uncomment.gate import gate_diff
from uncomment.model import ToolError

NOISY = "// Updated the constant as requested\nconst a = 1;\n"


def _tree(tmp_path: Path, files: dict[str, str]) -> Path:
    for rel, text in files.items():
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    return tmp_path


def _names(files: list[Path], root: Path) -> set[str]:
    return {f.resolve().relative_to(root.resolve()).as_posix() for f in files}


def test_matches_any_semantics():
    assert matches_any("a/_deps/x.c", ["_deps"])      # bare name matches at any depth
    assert matches_any("a/b/x.gen.go", ["*.gen.go"])
    assert matches_any("src/gen/x.py", ["src/**"])
    assert matches_any("gen/x.py", ["**/gen/*.py"])   # ** also matches zero segments
    assert not matches_any("src/deps_x/f.c", ["_deps"])
    assert not matches_any("other/x.py", ["src/**"])


def test_exclude_prunes_dirs_anywhere(tmp_path):
    root = _tree(tmp_path, {
        "src/a.js": "const a = 1;\n",
        "tests/unit/build-nj/_deps/unity/u.c": "int u;\n",
        "x/_deps/y.c": "int y;\n",
    })
    found = discover_files([root], Config(exclude=["_deps"]))
    assert _names(found, root) == {"src/a.js"}


def test_exclude_glob_patterns(tmp_path):
    root = _tree(tmp_path, {
        "a.gen.go": "package a\n",
        "b.go": "package b\n",
        "gen/c.go": "package c\n",
    })
    found = discover_files([root], Config(exclude=["*.gen.go", "gen/**"]))
    assert _names(found, root) == {"b.go"}


def test_include_narrows_without_pruning_parents(tmp_path):
    root = _tree(tmp_path, {
        "src/deep/a.js": "const a = 1;\n",
        "tools/b.js": "const b = 1;\n",
    })
    found = discover_files([root], Config(include=["src/**"], respect_gitignore=False))
    assert _names(found, root) == {"src/deep/a.js"}


def test_explicit_file_bypasses_filters(tmp_path):
    p = _tree(tmp_path, {"gen/a.js": NOISY}) / "gen" / "a.js"
    found = discover_files([p], Config(exclude=["gen/**", "a.js"]))
    assert found == [p]


def test_generated_markers(tmp_path):
    root = _tree(tmp_path, {
        "pb.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
        "fb.js": "/**\n * @generated by codegen\n */\nconst a = 1;\n",
        "human.c": "// do not edit this list without telling the driver team\nint x;\n",
    })
    assert is_generated(root / "pb.go")
    assert is_generated(root / "fb.js")
    # prose "do not edit" in lowercase is not a generated marker
    assert not is_generated(root / "human.c")
    found = discover_files([root], Config(respect_gitignore=False))
    assert _names(found, root) == {"human.c"}
    kept = discover_files([root], Config(skip_generated=False, respect_gitignore=False))
    assert len(kept) == 3


def test_respect_gitignore(tmp_path):
    if shutil.which("git") is None:
        pytest.skip("git not available")
    root = _tree(tmp_path, {
        "kept.js": "const a = 1;\n",
        "sdkconfig-out/out.js": "const b = 1;\n",
        ".gitignore": "sdkconfig-out/\n",
    })
    subprocess.run(["git", "init", "-q"], cwd=root, check=True, capture_output=True)
    found = discover_files([root], Config())
    assert _names(found, root) == {"kept.js"}
    found = discover_files([root], Config(respect_gitignore=False))
    assert _names(found, root) == {"kept.js", "sdkconfig-out/out.js"}


def test_gitignore_is_noop_outside_a_repo(tmp_path):
    root = _tree(tmp_path, {"a.js": "const a = 1;\n", ".gitignore": "a.js\n"})
    assert _names(discover_files([root], Config()), root) == {"a.js"}


def test_gate_diff_respects_exclude_and_generated(tmp_path, monkeypatch):
    import difflib

    monkeypatch.chdir(tmp_path)
    _tree(tmp_path, {
        "a.js": NOISY,
        "gen/b.js": "// Code generated by tool. DO NOT EDIT.\n" + NOISY,
        "vendor/c.js": NOISY,
    })

    def udiff(name: str, new: str) -> str:
        lines = difflib.unified_diff([], new.splitlines(), fromfile=f"a/{name}", tofile=f"b/{name}", lineterm="")
        return "\n".join(lines) + "\n"

    diff = udiff("a.js", NOISY) + udiff("gen/b.js", (tmp_path / "gen" / "b.js").read_text()) + udiff("vendor/c.js", NOISY)
    result = gate_diff(diff, Config(exclude=["vendor"]))
    assert result.files_scanned == 1
    assert result.files_skipped == 2
    assert all("a.js" in str(f.path) for f in result.findings)


def test_cli_exclude_flag(tmp_path, capsys, monkeypatch):
    monkeypatch.chdir(tmp_path)
    _tree(tmp_path, {"a.js": NOISY, "skipme/b.js": NOISY})
    main(["check", ".", "--exclude", "skipme", "--fail-on", "never", "--format", "json"])
    doc = json.loads(capsys.readouterr().out)
    assert doc["stats"]["files_scanned"] == 1


def test_empty_pattern_is_a_config_error(tmp_path):
    (tmp_path / "uncomment.toml").write_text('exclude = ["ok", "//"]\n', encoding="utf-8")
    with pytest.raises(ToolError, match="empty pattern"):
        load_config(tmp_path)
