"""Java/C#/Kotlin/Swift pack: grammar quirks and per-language directives."""

from __future__ import annotations

from unwaffle.config import Config
from unwaffle.extract import extract_source
from unwaffle.filtering import is_generated
from unwaffle.languages import CSHARP, JAVA, KOTLIN, SWIFT
from unwaffle.rules import run_rules


def _findings(path: str, src: str, spec):
    return run_rules(extract_source(path, src, spec), Config())


def test_kotlin_function_name_and_body_resolve():
    # kotlin's function_declaration has no name/body fields; the fallback
    # scan must still attribute density findings to the right function
    src = (
        "fun saturate(x: Int): Int {\n"
        "    // step one of the clamping story\n"
        "    // step two of the clamping story\n"
        "    // step three of the clamping story\n"
        "    // step four of the clamping story\n"
        "    return x\n"
        "}\n"
    )
    uc006 = [f for f in _findings("t.kt", src, KOTLIN) if f.rule == "UC006"]
    assert uc006 and "'saturate'" in uc006[0].message


def test_swift_mark_and_lint_directives_exempt():
    src = (
        "// MARK: - Session state\n"
        "// swiftlint:disable identifier_name\n"
        "let kBackoff = 50\n"
        "// swiftlint:enable identifier_name\n"
    )
    assert _findings("t.swift", src, SWIFT) == []


def test_swift_doc_callouts_are_structured_docs():
    src = (
        "/// Retries the fetch.\n"
        "/// - Parameter fetch: transport callback\n"
        "/// - Returns: the raw record\n"
        "func retry(_ fetch: () -> String) -> String { return fetch() }\n"
    )
    rules = {f.rule for f in _findings("t.swift", src, SWIFT)}
    assert "UC007" not in rules and "UC008" not in rules


def test_java_formatter_and_nls_directives_exempt():
    src = (
        "// @formatter:off\n"
        'String s = "x"; //$NON-NLS-1$\n'
        "// @formatter:on\n"
    )
    assert _findings("t.java", src, JAVA) == []


def test_csharp_auto_generated_header_skips_file(tmp_path):
    p = tmp_path / "gen.cs"
    p.write_text("// <auto-generated/>\nclass G { }\n", encoding="utf-8")
    assert is_generated(p)


def test_csharp_xml_docs_are_doc_comments():
    src = (
        "/// <summary>Maps a scan code to a key.</summary>\n"
        "/// <param name=\"code\">raw scan code</param>\n"
        "int Map(int code) { return code; }\n"
    )
    from unwaffle.model import Kind

    sf = extract_source("t.cs", src, CSHARP)
    assert sf.comments and sf.comments[0].kind is Kind.DOC
