"""Configuration: thresholds, disabled rules, severity overrides.

Loaded from `uncomment.toml` (bare keys or a `[tool.uncomment]` table both
work) or `[tool.uncomment]` in `pyproject.toml`, searched upward from the
scanned path. Invalid keys, types, or values are hard errors (exit code 2):
a silently ignored typo in CI is worse than a failed run.
"""

from __future__ import annotations

import re
import tomllib
from dataclasses import dataclass, field, fields
from pathlib import Path

from .model import Severity, ToolError

_RULE_ID_RE = re.compile(r"^(UC|STE)\d*$")


@dataclass
class Config:
    # UC001 restates-code
    restate_overlap: float = 0.6
    # UC005 commented-out code: fraction of code-looking lines
    code_line_fraction: float = 0.5
    # UC006 density: interior comment lines / body lines
    max_function_comment_ratio: float = 0.4
    min_interior_comment_lines: int = 4
    # UC008 doc migration: comment length that suggests real documentation
    doc_migration_lines: int = 12
    # UC009 trailing comment limits; 80 chars sits above median veteran
    # practice (jsoup's house style medians at 75), the word cap catches
    # agent chatter regardless
    max_trailing_chars: int = 80
    max_trailing_words: int = 10
    # UC007 threshold
    redundant_doc_overlap: float = 0.75
    # UC012: when true, ANY non-ASCII character in a comment is flagged,
    # not just emoji/decorative symbols
    ascii_comments: bool = False
    # gate: baseline comments at least this similar to a new comment count as
    # the same comment (typo fixes and light rewording are not "new")
    baseline_similarity: float = 0.85
    # gate: comment flood (noisy new comment lines vs added code lines)
    flood_ratio: float = 0.75
    flood_min_lines: int = 12
    # gate: comment amplification (UC101) — new prose comment lines added to a
    # file that already had prose comments, even when each one evades the
    # per-comment rules
    growth_min_lines: int = 6
    growth_factor: float = 1.0
    # STE limits
    ste_max_sentence_words: int = 20
    ste_max_paragraph_sentences: int = 6
    # cap on INFO findings per rule per file; the rest collapse into one summary
    max_hints_per_rule: int = 8
    # ASCII-only tool output when false (same as --ascii), always Unicode
    # when true; unset means automatic — ASCII when stdout is not
    # UTF-8-capable (legacy Windows consoles and pipes)
    unicode_output: bool | None = None

    # input filtering with gitignore-flavored globs: a pattern without '/'
    # matches any path component ("_deps"), one with '/' matches the path
    # relative to the scan root ("src/**", "**/gen/*.py"). Applies to
    # directory walks, diff selection, and the baseline sweep — never to
    # files named explicitly on the command line
    include: list[str] = field(default_factory=list)
    exclude: list[str] = field(default_factory=list)
    # skip files whose head carries a generated-code marker (DO NOT EDIT,
    # @generated, automatically generated)
    skip_generated: bool = True
    # drop files git ignores (one `git check-ignore` batch per scanned root)
    respect_gitignore: bool = True

    # extra regexes (matched against comment content) treated as tooling
    # directives: exempt from all rules, e.g. ["^MY-LINT:", "^generated by"]
    directive_patterns: list[str] = field(default_factory=list)

    # project vocabulary the wording rules (UC002/UC003/STE02/STE03) must not
    # judge: product names and domain terms, e.g. ["Let's Encrypt", "leverage"].
    # A term with an uppercase letter matches exactly; all-lowercase matches
    # any case — so approving "Let's Encrypt" keeps "let's encrypt the
    # payload" flagged as narration
    approved_terms: list[str] = field(default_factory=list)

    # extra policy lines appended to the agent-format corrective prompt:
    # house rules like "Long design prose goes to docs/architecture.md."
    agent_policy: list[str] = field(default_factory=list)

    disable: list[str] = field(default_factory=list)
    severity: dict[str, str] = field(default_factory=dict)

    def rule_enabled(self, rule_id: str) -> bool:
        return not any(rule_id.startswith(d) for d in self.disable)

    def severity_override(self, rule_id: str) -> Severity | None:
        name = self.severity.get(rule_id)
        return Severity.parse(name) if name else None


def parse_disable_arg(value: str) -> list[str]:
    """Split and validate a --disable argument; empty or malformed ids are
    errors because prefix matching would otherwise disable far too much."""
    entries = [e.strip() for e in value.split(",")]
    for e in entries:
        if not _RULE_ID_RE.match(e):
            raise ToolError(
                f"invalid rule id in --disable: '{e}' (expected UC/STE optionally followed by digits)"
            )
    return entries


def _from_table(table: dict, source: str) -> Config:
    cfg = Config()
    valid = {f.name for f in fields(Config)}
    errors: list[str] = []

    for key, value in table.items():
        norm = key.replace("-", "_")
        if norm not in valid:
            errors.append(f"unknown key '{key}'")
            continue
        default = getattr(cfg, norm)
        if default is None:
            ok = isinstance(value, bool)  # tri-state booleans (unicode-output)
        elif isinstance(default, bool):
            ok = isinstance(value, bool)
        elif isinstance(default, float):
            ok = isinstance(value, (int, float)) and not isinstance(value, bool)
            value = float(value) if ok else value
        elif isinstance(default, int):
            ok = isinstance(value, int) and not isinstance(value, bool)
        elif isinstance(default, list):
            ok = isinstance(value, list) and all(isinstance(v, str) for v in value)
        elif isinstance(default, dict):
            ok = isinstance(value, dict)
        else:
            ok = isinstance(value, str)
        if not ok:
            errors.append(f"key '{key}': expected {type(default).__name__}, got {value!r}")
            continue
        setattr(cfg, norm, value)

    for rule_id, name in cfg.severity.items():
        if not _RULE_ID_RE.match(rule_id):
            errors.append(f"severity: '{rule_id}' is not a rule id")
        elif not isinstance(name, str) or name.lower() not in ("info", "warn", "error"):
            errors.append(f"severity for {rule_id}: {name!r} is not one of info/warn/error")
    for entry in cfg.disable:
        if not _RULE_ID_RE.match(entry):
            errors.append(f"disable: '{entry}' is not a rule id or UC/STE prefix")
    for pattern in cfg.directive_patterns:
        try:
            re.compile(pattern)
        except re.error as exc:
            errors.append(f"directive-patterns: invalid regex {pattern!r} ({exc})")
    for term in cfg.approved_terms:
        if not term.strip():
            errors.append("approved-terms: empty term")
    for key_name, patterns in (("include", cfg.include), ("exclude", cfg.exclude)):
        for pattern in patterns:
            if not pattern.strip().strip("/"):
                errors.append(f"{key_name}: empty pattern")
    for line in cfg.agent_policy:
        if not line.strip():
            errors.append("agent-policy: empty line")

    if errors:
        raise ToolError(f"invalid configuration in {source}: " + "; ".join(errors))
    return cfg


def _load_toml(path: Path) -> dict:
    try:
        with open(path, "rb") as fh:
            return tomllib.load(fh)
    except tomllib.TOMLDecodeError as exc:
        raise ToolError(f"invalid TOML in {path}: {exc}") from exc


def _unwrap(data: dict) -> dict:
    """Accept both bare keys and a [tool.uncomment] table."""
    tool = data.get("tool")
    if isinstance(tool, dict) and isinstance(tool.get("uncomment"), dict):
        return tool["uncomment"]
    return {k: v for k, v in data.items() if k != "tool"}


def load_config(start: str | Path = ".", explicit: str | None = None) -> Config:
    if explicit:
        if not Path(explicit).is_file():
            raise ToolError(f"config file does not exist: {explicit}")
        return _from_table(_unwrap(_load_toml(Path(explicit))), explicit)

    directory = Path(start).resolve()
    if directory.is_file():
        directory = directory.parent
    for candidate_dir in [directory, *directory.parents]:
        toml_path = candidate_dir / "uncomment.toml"
        if toml_path.is_file():
            return _from_table(_unwrap(_load_toml(toml_path)), str(toml_path))
        pyproject = candidate_dir / "pyproject.toml"
        if pyproject.is_file():
            data = _load_toml(pyproject)
            table = data.get("tool", {}).get("uncomment")
            if table is not None:
                return _from_table(table, str(pyproject))
    return Config()
